### PR TITLE
Add support for swift package manager

### PR DESCRIPTION
**Pull request by tahirmt**
Add support for swift package manager. Also changes the minimum deployment version to iOS 9.

Refactor some code to use implicit return

### CODE REVIEW

**Comment by ketenshi** [comment]
Do you mind updating the README for installing with SPM?

**Comment by tahirmt** [comment]
> Do you mind updating the README for installing with SPM?

@ketenshi done

**Review by alexsm20 — APPROVED** [review]
I'm assuming changing the deployment target from iOS 8 to iOS 9 was required due to SPM not supporting it?

**Comment by tahirmt** [comment]
> I'm assuming changing the deployment target from iOS 8 to iOS 9 was required due to SPM not supporting it?

Yeah Quick and Nimble required iOS 9 and no one is building for iOS 8 anyway so

**Review by francocarbonaro — APPROVED** [review]

**Review by ketenshi — APPROVED** [review]

**Pull request merged**
